Output demos/readme_demo.gif
Set FontSize 18
Set Width 1000
Set Height 500
Set Theme "Catppuccin Macchiato"

Hide
Type "cargo run -- demos/readme_demo.json"
Enter
Sleep 1s

Show
Type "5j"
Type "R"
Type "3 5 7 5"
Sleep 500ms
Escape
Type "kl"
Type "R"
Type "3 5 7 5"
Sleep 500ms
Escape
Type "vb"
Sleep 500ms
Type "y"
Sleep 500ms
Type "w"
Sleep 500ms
Type "p"
Sleep 500ms
Type "ll"
Sleep 500ms
Type "<<<<<<"
Sleep 500ms
Type "hh"
Sleep 500ms
Type "A"
Sleep 500ms
Type "With Distortion"
Enter
Sleep 1s